import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Reveal } from "@/components/Reveal";
import { Counter } from "@/components/Counter";

export const Route=createFileRoute("/about")({head:()=>({meta:[{title:"About the Studio — FlawByte"},{name:"description",content:"Meet FlawByte, the Hyderabad creative technology studio founded by Kamatam Akhil."},{property:"og:title",content:"About the Studio — FlawByte"},{property:"og:description",content:"The thinking, process and founder story behind FlawByte."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/about"}]}),component:About});
const chapters=[
{label:"Who we are",title:"A small studio with a wide field of view.",body:"FlawByte brings design, development, social and film together. The work is collaborative, direct and shaped around the business behind the brief."},
{label:"How we think",title:"Clarity before decoration.",body:"We look for the clearest idea, then give it a memorable form. Every choice should help someone understand, trust or act."},
{label:"How we work",title:"Close to the problem. Fast on the craft.",body:"A tight team means fewer handoffs and more attention. We discover, define, design and build as one continuous process."},
{label:"What we build",title:"Brands people can experience.",body:"Identity systems, websites, campaigns, reels and films—designed to feel consistent wherever a customer meets them."},
{label:"Why FlawByte",title:"Senior-quality thinking without the distance.",body:"We care about the details, communicate plainly and stay involved from the first conversation through launch."}];
const timeline=[{year:"2021",title:"The first sketch",desc:"At 16, Kamatam Akhil started freelancing—designing posters and edits from his bedroom."},{year:"2023",title:"Building the craft",desc:"Two years of hands-on client work across brands, reels and websites."},{year:"2024",title:"The idea for FlawByte",desc:"The vision for a focused studio serving founders begins to take shape."},{year:"2025",title:"FlawByte begins",desc:"Akhil launches the studio after years spent learning by making."},{year:"2026",title:"Still moving forward",desc:"At 20, Akhil continues building FlawByte around care, speed and ambitious work."}];
function About(){return <><section className="border-b border-border py-20 md:py-32"><div className="container-x"><Reveal><p className="editorial-label text-primary">About FlawByte</p><h1 className="mt-6 max-w-[11ch] text-5xl font-semibold leading-[.96] md:text-8xl">A young studio with years in the work.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-ink-soft">Founded by Kamatam Akhil, who started creating for clients at 16 and is now 20.</p></Reveal></div></section>
<section className="py-16 md:py-28"><div className="container-x">{chapters.map((c,i)=><Reveal key={c.label}><article className="grid gap-7 border-t border-border py-12 md:grid-cols-12 md:py-20"><div className="md:col-span-3"><p className="editorial-label text-primary">0{i+1} — {c.label}</p></div><div className="md:col-span-5"><h2 className="text-3xl font-semibold leading-tight md:text-5xl">{c.title}</h2></div><div className="md:col-span-4"><p className="max-w-md leading-7 text-ink-soft">{c.body}</p></div></article></Reveal>)}</div></section>
<section className="border-y border-border bg-surface py-24 md:py-32"><div className="container-x"><Reveal><p className="editorial-label text-primary">The journey</p><h2 className="mt-5 text-4xl font-semibold md:text-6xl">Made by doing.</h2></Reveal><div className="mt-14 border-t border-border">{timeline.map(t=><Reveal key={t.year}><div className="grid gap-3 border-b border-border py-7 md:grid-cols-[160px_1fr_2fr] md:items-baseline"><p className="text-3xl font-semibold text-primary">{t.year}</p><h3 className="font-semibold">{t.title}</h3><p className="text-sm leading-6 text-ink-soft">{t.desc}</p></div></Reveal>)}</div></div></section>
<section className="py-24 md:py-32"><div className="container-x"><div className="grid grid-cols-2 border-y border-border md:grid-cols-4">{[{n:3,l:"Years crafting"},{n:20,l:"Projects shipped"},{n:150,l:"Happy clients"},{n:3000,l:"Cups of coffee"}].map(s=><div key={s.l} className="border-r border-border py-10 text-center last:border-r-0"><div className="text-4xl font-semibold md:text-6xl"><Counter to={s.n} suffix="+"/></div><p className="mt-2 text-xs uppercase text-ink-soft">{s.l}</p></div>)}</div><div className="mt-16 flex flex-col justify-between gap-8 md:flex-row md:items-center"><h2 className="max-w-2xl text-4xl font-semibold md:text-6xl">Bring us something worth caring about.</h2><Link to="/contact" className="inline-flex min-h-12 items-center gap-2 rounded-md bg-dark px-6 text-sm font-semibold text-dark-foreground">Work with us <ArrowRight size={15}/></Link></div></div></section></>}
