import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Mail, MapPin, Phone } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Reveal } from "@/components/Reveal";

export const Route=createFileRoute("/contact")({head:()=>({meta:[{title:"Start a Project — FlawByte"},{name:"description",content:"Tell FlawByte about your next brand, website, social media or film project."},{property:"og:title",content:"Start a Project — FlawByte"},{property:"og:description",content:"Have something worth building? Start a conversation with FlawByte."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/contact"}]}),component:Contact});
function Contact(){return <><section className="border-b border-border py-20 md:py-32"><div className="container-x"><Reveal><p className="editorial-label text-primary">Start a conversation</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.96] md:text-8xl">Have something worth building?</h1><p className="mt-8 max-w-xl text-lg leading-8 text-ink-soft">Tell us what you are making, changing or trying to grow.</p></Reveal></div></section><section className="py-20 md:py-28"><div className="container-x grid gap-16 lg:grid-cols-12"><Reveal className="lg:col-span-4"><p className="editorial-label text-ink-soft">Direct contact</p><div className="mt-7 space-y-6"><ContactLine icon={<Mail size={17}/>} label="Email" value="flawbyte@gmail.com" href="mailto:flawbyte@gmail.com"/><ContactLine icon={<Phone size={17}/>} label="Phone" value="+91 6302431662" href="tel:+916302431662"/><ContactLine icon={<MapPin size={17}/>} label="Studio" value="Hyderabad, Telangana"/></div><p className="mt-12 max-w-sm text-sm leading-6 text-ink-soft">Prefer email? Write directly and include your goal, timeline and what you need help with.</p></Reveal><Reveal delay={.08} className="lg:col-span-7 lg:col-start-6"><ContactForm/></Reveal></div></section></>}
function ContactLine({icon,label,value,href}:{icon:React.ReactNode;label:string;value:string;href?:string}){const body=<><span className="text-primary">{icon}</span><span><span className="editorial-label block text-ink-soft">{label}</span><span className="mt-1 block text-sm font-semibold">{value}</span></span></>;return href?<a href={href} className="flex items-start gap-4 hover:text-primary">{body}</a>:<div className="flex items-start gap-4">{body}</div>}
function ContactForm(){const [values,setValues]=useState({name:"",email:"",company:"",project:"",budget:"",message:""}); const submit=(e:FormEvent)=>{e.preventDefault();const subject=encodeURIComponent(`Project enquiry from ${values.name}`);const body=encodeURIComponent(`Name: ${values.name}\nEmail: ${values.email}\nCompany: ${values.company||"Not provided"}\nProject type: ${values.project}\nBudget: ${values.budget}\n\n${values.message}`);window.location.href=`mailto:flawbyte@gmail.com?subject=${subject}&body=${body}`};return <form onSubmit={submit}><div className="grid gap-x-6 gap-y-8 sm:grid-cols-2"><Field label="Name" required value={values.name} set={v=>setValues(s=>({...s,name:v}))}/><Field label="Email" type="email" required value={values.email} set={v=>setValues(s=>({...s,email:v}))}/><Field label="Company" value={values.company} set={v=>setValues(s=>({...s,company:v}))}/><Select label="Project type" required value={values.project} set={v=>setValues(s=>({...s,project:v}))} options={["Brand Identity","Website","Social Media","Graphic Design","Video Editing","Instant Reels","Something else"]}/><Select label="Budget" required value={values.budget} set={v=>setValues(s=>({...s,budget:v}))} options={["Under ₹25,000","₹25,000–₹50,000","₹50,000–₹1,00,000","₹1,00,000+","Let's discuss"]}/><div className="sm:col-span-2"><label className="editorial-label text-ink-soft" htmlFor="message">Message</label><textarea id="message" required rows={5} value={values.message} onChange={e=>setValues(s=>({...s,message:e.target.value}))} className="mt-3 w-full resize-none border-x-0 border-b border-t-0 border-border bg-transparent px-0 py-3 outline-none focus:border-primary"/></div></div><div className="mt-10 flex flex-col items-start justify-between gap-5 sm:flex-row sm:items-center"><p className="max-w-xs text-xs leading-5 text-ink-soft">This opens your email app. By continuing, you agree to our <Link to="/privacy" className="underline">privacy policy</Link>.</p><button type="submit" className="group inline-flex min-h-12 items-center gap-2 rounded-md bg-dark px-6 text-sm font-semibold text-dark-foreground transition-colors hover:bg-primary">Start a conversation <ArrowRight size={15} className="transition-transform group-hover:translate-x-1"/></button></div></form>}
function Field({label,value,set,type="text",required=false}:{label:string;value:string;set:(v:string)=>void;type?:string;required?:boolean}){const id=label.toLowerCase().replace(/ /g,"-");return <label className="block" htmlFor={id}><span className="editorial-label text-ink-soft">{label}</span><input id={id} type={type} required={required} value={value} onChange={e=>set(e.target.value)} className="mt-3 w-full border-x-0 border-b border-t-0 border-border bg-transparent px-0 py-3 outline-none focus:border-primary"/></label>}
function Select({label,value,set,options,required}:{label:string;value:string;set:(v:string)=>void;options:string[];required?:boolean}){const id=label.toLowerCase().replace(/ /g,"-");return <label className="block" htmlFor={id}><span className="editorial-label text-ink-soft">{label}</span><select id={id} required={required} value={value} onChange={e=>set(e.target.value)} className="mt-3 w-full border-x-0 border-b border-t-0 border-border bg-transparent px-0 py-3 outline-none focus:border-primary"><option value="">Select one</option>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
