import { createFileRoute, Link } from "@tanstack/react-router";
import { motion, useMotionValue, useSpring } from "motion/react";
import { ArrowDown, ArrowRight, ArrowUpRight } from "lucide-react";
import { useRef } from "react";
import { Reveal, Stagger, StaggerItem } from "@/components/Reveal";
import { MagneticButton } from "@/components/MagneticButton";
import { Marquee } from "@/components/Marquee";
import { Counter } from "@/components/Counter";
import { ProjectCover } from "@/components/ProjectCover";
import { clientNames, projects, testimonials, whatsappUrl } from "@/lib/site-data";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "FlawByte — Digital Experiences That Grow Brands" },
    { name: "description", content: "FlawByte is a creative technology studio in Hyderabad building brands, websites, social campaigns and films for ambitious businesses." },
    { property: "og:title", content: "FlawByte — Digital Experiences That Grow Brands" },
    { property: "og:description", content: "A creative technology studio building brands, websites, social campaigns and films." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ], links: [{ rel: "canonical", href: "https://flawbyte.com/" }] }), component: Home,
});

const services = [
  { n:"01", title:"Social Media Marketing", desc:"Strategy, content and paid growth designed to compound.", href:"/pricing#social-media", visual:"social" },
  { n:"02", title:"Website Design & Development", desc:"High-conversion digital experiences engineered for speed and scale.", href:"/pricing#website-development", visual:"web" },
  { n:"03", title:"Graphic Design", desc:"Coherent visual systems, posters and social creatives.", href:"/pricing#graphic-design", visual:"type" },
  { n:"04", title:"Video Editing", desc:"Cinematic cuts, campaigns and films tuned for attention.", href:"/pricing#video-editing", visual:"video" },
  { n:"05", title:"Instant Reels", desc:"Trend-native vertical content delivered with speed.", href:"/pricing#instant-reels", visual:"reels" },
  { n:"06", title:"Brand Identity", desc:"Names, marks and systems built to stay memorable.", href:"/pricing#brand-identity", visual:"brand" },
];

function Home() {
  return <>
    <Hero />
    <section className="border-y border-border bg-paper py-10"><div className="container-x"><p className="editorial-label mb-7 text-center text-ink-soft">Trusted by ambitious teams</p><Marquee items={clientNames}/></div></section>
    <section className="py-24 md:py-36"><div className="container-x"><SectionHeading label="What we do" title="One studio. Every part of your digital presence." link="/services" />
      <div className="mt-16 border-t border-border">{services.map((s,i)=><ServiceRow key={s.title} {...s} reverse={i%2===1}/>)}</div>
    </div></section>
    <section className="border-y border-border bg-surface py-24 md:py-36"><div className="container-x">
      <Reveal><p className="editorial-label text-primary">How we work</p><h2 className="mt-5 max-w-4xl text-4xl font-semibold leading-[1.05] md:text-7xl">We're built like a product team, not an agency.</h2></Reveal>
      <div className="mt-16 grid grid-cols-2 border-l border-t border-border md:grid-cols-6">{["Discover","Strategy","Design","Build","Launch","Grow"].map((step,i)=><motion.div whileHover={{ y: -5 }} transition={{ duration: .25 }} key={step} className="group relative border-b border-r border-border p-5 transition-colors hover:bg-paper md:min-h-32"><span className="text-xs text-ink-soft">0{i+1}</span><p className="mt-8 text-sm font-semibold uppercase transition-colors group-hover:text-primary">{step}</p>{i<5&&<ArrowRight size={14} className="absolute right-3 top-1/2 hidden text-primary transition-transform group-hover:translate-x-1 md:block"/>}</motion.div>)}</div>
      <div className="mt-16 grid gap-8 border-t border-border pt-10 md:grid-cols-4">{[["Creative","Original, art-directed work."],["Fast delivery","Momentum from day one."],["Results driven","Decisions tied to your goals."],["Modern technology","Built for speed and longevity."]].map(([a,b],i)=><Reveal key={a} delay={i*.05}><p className="editorial-label text-primary">0{i+1}</p><h3 className="mt-4 text-xl font-semibold">{a}</h3><p className="mt-2 text-sm text-ink-soft">{b}</p></Reveal>)}</div>
      <div className="mt-24 grid grid-cols-2 border-y border-border md:grid-cols-4">{[{n:3,l:"Years crafting"},{n:20,l:"Projects shipped"},{n:150,l:"Happy clients"},{n:3000,l:"Cups of coffee"}].map((s)=><div key={s.l} className="border-r border-border py-8 text-center last:border-r-0 md:py-12"><div className="text-4xl font-semibold md:text-6xl"><Counter to={s.n} suffix="+"/></div><p className="mt-2 text-xs uppercase text-ink-soft">{s.l}</p></div>)}</div>
    </div></section>
    <section className="py-24 md:py-36"><div className="container-x"><SectionHeading label="Selected work" title="Made to belong to the brand—not the trend." link="/portfolio" />
      <div className="mt-16 grid gap-x-6 gap-y-12 md:grid-cols-12">{projects.slice(0,3).map((p,i)=><Reveal key={p.slug} className={i===0?"md:col-span-7":"md:col-span-5"}><a href={p.url} target="_blank" rel="noopener noreferrer" aria-label={`View ${p.title} project`} className="group block"><ProjectCover project={p} className="aspect-[4/3]"/><div className="mt-5 flex items-start justify-between border-t border-border pt-5 transition-colors group-hover:border-primary"><div className="transition-transform group-hover:translate-x-1"><p className="text-xs uppercase text-ink-soft">{p.category} · {p.year}</p><h3 className="mt-2 text-2xl font-semibold">{p.title}</h3><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold uppercase text-primary">View Project <ArrowUpRight size={14}/></span></div><ArrowUpRight className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" size={20}/></div></a></Reveal>)}</div>
    </div></section>
    <section className="border-y border-border bg-paper py-24 md:py-36"><div className="container-x"><Reveal><p className="editorial-label text-primary">In their words</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold md:text-6xl">Trust is built in the work.</h2></Reveal><div className="mt-16 grid border-t border-border md:grid-cols-3">{testimonials.map((t,i)=><Reveal key={t.name} delay={i*.06}><figure className="h-full border-b border-border py-8 md:border-r md:px-8 md:first:pl-0 md:last:border-r-0"><blockquote className="text-xl leading-relaxed">“{t.quote}”</blockquote><figcaption className="mt-10 text-sm font-semibold">{t.name}<span className="mt-1 block text-xs font-normal text-ink-soft">{t.role}</span></figcaption></figure></Reveal>)}</div></div></section>
    <FinalCTA />
  </>;
}

function Hero(){const ref=useRef<HTMLElement>(null); const mx=useMotionValue(0); const my=useMotionValue(0); const x=useSpring(mx,{stiffness:45,damping:20}); const y=useSpring(my,{stiffness:45,damping:20}); return <section ref={ref} onMouseMove={(e)=>{const r=e.currentTarget.getBoundingClientRect();mx.set((e.clientX-r.left-r.width/2)/55);my.set((e.clientY-r.top-r.height/2)/55)}} onMouseLeave={()=>{mx.set(0);my.set(0)}} className="relative min-h-[calc(100svh-6rem)] overflow-hidden border-b border-border"><div aria-hidden className="absolute inset-0 bg-hero-atmosphere"/><div className="container-x relative flex min-h-[calc(100svh-6rem)] flex-col justify-center py-16"><div className="grid items-center gap-14 lg:grid-cols-12"><div className="lg:col-span-8"><p className="editorial-label text-primary">Creative technology studio · Hyderabad</p><h1 className="mt-6 max-w-[11ch] text-5xl font-semibold leading-[.98] md:text-7xl lg:text-[86px]">Building digital experiences that <span className="text-gradient">grow brands.</span></h1><p className="mt-8 max-w-xl text-base leading-7 text-ink-soft md:text-lg">FlawByte creates premium digital experiences across brand, social, web and film—thoughtfully designed as one connected system.</p><div className="mt-10 flex flex-wrap gap-3"><a href={whatsappUrl} target="_blank" rel="noopener noreferrer"><MagneticButton>Let&apos;s Talk <ArrowUpRight size={15}/></MagneticButton></a><Link to="/portfolio"><MagneticButton variant="outline">View Our Work <ArrowUpRight size={15}/></MagneticButton></Link></div></div><motion.div style={{x,y}} className="relative hidden aspect-square lg:col-span-4 lg:block"><GrowthComposition/></motion.div></div><a href="#work" className="absolute bottom-7 left-5 flex items-center gap-2 text-xs font-semibold uppercase text-ink-soft">Scroll <ArrowDown size={14}/></a></div></section>}

function GrowthComposition(){return <div className="relative h-full border border-border bg-paper/70 p-7 shadow-card"><div className="flex justify-between text-[10px] uppercase text-ink-soft"><span>FlawByte system</span><span>Live</span></div><div className="absolute inset-x-7 top-1/3 h-px bg-border"/><div className="absolute inset-x-7 top-2/3 h-px bg-border"/><div className="absolute inset-y-7 left-1/3 w-px bg-border"/><div className="absolute inset-y-7 left-2/3 w-px bg-border"/><div className="absolute left-[22%] top-[48%] h-3 w-3 rounded-full bg-primary"/><div className="absolute right-[20%] top-[23%] border-l border-primary pl-3 text-xs">Brand</div><div className="absolute bottom-[18%] left-[44%] border-t border-primary pt-3 text-xs">Build</div><svg aria-hidden viewBox="0 0 300 300" className="absolute inset-10"><path d="M20 245 C80 230 84 180 130 174 S190 130 210 85 S252 48 280 28" fill="none" stroke="currentColor" className="text-primary" strokeWidth="1.5"/><circle cx="20" cy="245" r="3" fill="currentColor"/><circle cx="130" cy="174" r="3" fill="currentColor"/><circle cx="210" cy="85" r="3" fill="currentColor"/></svg></div>}

function SectionHeading({label,title,link}:{label:string;title:string;link:string}){return <div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><Reveal><p className="editorial-label text-primary">{label}</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold leading-[1.05] md:text-6xl">{title}</h2></Reveal><Link to={link} className="group inline-flex items-center gap-2 text-sm font-semibold">Explore all <ArrowUpRight size={15} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></Link></div>}

function ServiceRow({n,title,desc,href,visual,reverse}:{n:string;title:string;desc:string;href:string;visual:string;reverse:boolean}){return <Reveal><a id={n==="01"?"work":undefined} href={href} className="group grid items-center gap-8 border-b border-border py-10 md:grid-cols-12 md:py-14"><div className={reverse?"md:order-2 md:col-span-5":"md:col-span-5"}><div className="editorial-label text-primary">{n} — Service</div><h3 className="mt-5 max-w-md text-3xl font-semibold transition-transform duration-300 group-hover:translate-x-1 md:text-4xl">{title}</h3><p className="mt-4 max-w-md leading-7 text-ink-soft">{desc}</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-semibold">View pricing <ArrowRight size={15} className="transition-transform group-hover:translate-x-1"/></span></div><div className={reverse?"md:order-1 md:col-span-7":"md:col-span-7"}><div className="transition-transform duration-500 group-hover:-translate-y-1"><ServiceVisual type={visual}/></div></div></a></Reveal>}

function ServiceVisual({type}:{type:string}){return <div className="relative aspect-[16/8] overflow-hidden border border-border bg-surface p-6"><div className="absolute inset-0 opacity-60 [background-image:linear-gradient(var(--border)_1px,transparent_1px),linear-gradient(90deg,var(--border)_1px,transparent_1px)] [background-size:36px_36px]"/><div className="relative flex h-full items-center justify-center">{type==="web"?<div className="h-3/4 w-4/5 border border-ink/20 bg-paper p-4"><div className="flex gap-1 border-b border-border pb-3"><i className="h-1.5 w-1.5 rounded-full bg-primary"/><i className="h-1.5 w-1.5 rounded-full bg-border"/></div><div className="mt-6 h-3 w-2/3 bg-ink"/><div className="mt-3 h-2 w-1/2 bg-border"/></div>:type==="reels"?<div className="grid h-full w-full grid-cols-3 gap-3">{[1,2,3].map(i=><div key={i} className="border border-border bg-paper p-3"><div className="h-full border-l border-primary"/></div>)}</div>:type==="video"?<div className="w-full"><div className="mb-6 aspect-[16/5] border border-border bg-dark"/><div className="flex gap-1">{[2,4,3,6,2,5,3,4].map((x,i)=><i key={i} className="h-10 bg-primary/70" style={{flex:x}}/>)}</div></div>:type==="type"?<div className="grid w-full grid-cols-[1fr_2fr] items-end gap-6"><span className="text-8xl font-bold text-primary">Aa</span><div><div className="h-px bg-ink"/><p className="mt-4 text-2xl font-semibold">Type. Color. Rhythm.</p></div></div>:type==="brand"?<div className="grid aspect-square w-1/2 place-items-center border border-ink/20"><div className="grid h-20 w-20 place-items-center rounded-full bg-primary text-3xl font-bold text-primary-foreground">F</div></div>:<div className="grid w-full grid-cols-3 gap-3">{["POST","STORY","CAMPAIGN"].map((x,i)=><div key={x} className="aspect-square border border-border bg-paper p-3 text-[10px]"><span className={i===1?"text-primary":""}>{x}</span><div className="mt-8 h-px bg-ink/20"/></div>)}</div>}</div></div>}

function FinalCTA(){return <section className="relative overflow-hidden bg-dark py-24 text-dark-foreground md:py-36"><div aria-hidden className="absolute inset-0 bg-[radial-gradient(circle_at_70%_40%,color-mix(in_oklab,var(--primary)_28%,transparent),transparent_35%)]"/><div className="container-x relative"><Reveal><p className="editorial-label text-dark-foreground/55">Ready when you are</p><h2 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.98] md:text-8xl">Let&apos;s build something<br/><span className="text-primary-glow">people remember.</span></h2><div className="mt-12 flex flex-wrap gap-3"><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-md bg-paper px-6 text-sm font-semibold text-ink">Let&apos;s Talk <ArrowUpRight size={15}/></a><Link to="/portfolio" className="inline-flex min-h-12 items-center gap-2 rounded-md border border-dark-foreground/25 px-6 text-sm font-semibold">View Our Work <ArrowUpRight size={15}/></Link></div></Reveal></div></section>}
