import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check } from "lucide-react";
import { Reveal } from "@/components/Reveal";

export const Route=createFileRoute("/services")({head:()=>({meta:[{title:"Creative Services — FlawByte"},{name:"description",content:"Social media, websites, graphic design, video editing, instant reels and brand identity by FlawByte."},{property:"og:title",content:"Creative Services — FlawByte"},{property:"og:description",content:"Six focused creative and technology disciplines, delivered by one studio."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/services"}]}),component:Services});
const services=[
{title:"Social Media Marketing",tag:"01 — Growth",desc:"Full-funnel social strategy, from positioning to paid growth. Content that earns attention and campaigns that scale.",features:["Brand positioning","Content strategy","Campaign management","Growth strategy","Analytics & reporting"],href:"/pricing#social-media",type:"social"},
{title:"Website Design & Development",tag:"02 — Web",desc:"Sites engineered for speed, search and conversion. Design systems and custom builds that feel considered.",features:["Responsive design","SEO optimized","Performance-first","UI / UX design","Custom development"],href:"/pricing#website-development",type:"web"},
{title:"Graphic Design",tag:"03 — Visual",desc:"Cohesive visual systems, from brand marks to campaign creatives. Every asset on-brand and on-purpose.",features:["Branding","Posters & print","Social media designs","Motion graphics","Presentation decks"],href:"/pricing#graphic-design",type:"graphic"},
{title:"Video Editing",tag:"04 — Video",desc:"Cinematic ad edits, product films and reels. Cut for pacing, colored for mood and tuned for retention.",features:["Ads & commercials","Reels & shorts","Transitions & effects","Color grading","Sound design"],href:"/pricing#video-editing",type:"video"},
{title:"Instant Reels",tag:"05 — Speed",desc:"Trend-native reels shipped in minutes. Shot on iPhone, edited fast and tuned to what works now.",features:["Delivered in minutes","Shot on iPhone","Trend-based edits","Fast turnaround","Weekly retainers"],href:"/pricing#instant-reels",type:"reels"},
{title:"Brand Identity",tag:"06 — Brand",desc:"Names, marks, voice and systems. A brand that shows up consistently and grows with you.",features:["Logo design","Design systems","Brand guidelines","Voice & messaging","Naming"],href:"/pricing#brand-identity",type:"brand"}];
function Services(){return <><section className="border-b border-border py-20 md:py-32"><div className="container-x"><Reveal><p className="editorial-label text-primary">Capabilities</p><div className="mt-5 grid gap-8 md:grid-cols-12 md:items-end"><h1 className="text-5xl font-semibold leading-[.98] md:col-span-9 md:text-8xl">Six disciplines.<br/>One connected system.</h1><p className="text-sm leading-7 text-ink-soft md:col-span-3">Pick what you need, or bring us the whole challenge.</p></div></Reveal></div></section><section><div className="container-x">{services.map((s,i)=><Reveal key={s.title}><article className="grid gap-10 border-b border-border py-16 md:grid-cols-12 md:items-center md:py-24"><div className={i%2?"md:order-2 md:col-span-5":"md:col-span-5"}><p className="editorial-label text-primary">{s.tag}</p><h2 className="mt-5 text-3xl font-semibold md:text-5xl">{s.title}</h2><p className="mt-5 max-w-lg leading-7 text-ink-soft">{s.desc}</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{s.features.map(f=><li key={f} className="flex items-center gap-2 text-sm"><Check size={14} className="text-primary"/>{f}</li>)}</ul><a href={s.href} className="group mt-9 inline-flex items-center gap-2 text-sm font-semibold">View packages <ArrowRight size={15} className="transition-transform group-hover:translate-x-1"/></a></div><div className={i%2?"md:order-1 md:col-span-7":"md:col-span-7"}><ServiceArtwork type={s.type} title={s.title}/></div></article></Reveal>)}</div></section><section className="bg-dark py-24 text-dark-foreground"><div className="container-x flex flex-col justify-between gap-10 md:flex-row md:items-end"><h2 className="max-w-3xl text-5xl font-semibold leading-none md:text-7xl">Not sure where to start?</h2><Link to="/contact" className="inline-flex min-h-12 items-center gap-2 rounded-md bg-paper px-6 text-sm font-semibold text-ink">Let's discuss your project <ArrowRight size={15}/></Link></div></section></>}
function ServiceArtwork({type,title}:{type:string;title:string}){return <div className="relative aspect-[16/9] overflow-hidden border border-border bg-surface p-7"><div className="absolute inset-0 opacity-70 [background-image:linear-gradient(var(--border)_1px,transparent_1px),linear-gradient(90deg,var(--border)_1px,transparent_1px)] [background-size:42px_42px]"/><div className="relative flex h-full items-center justify-center">{type==="web"?<div className="h-4/5 w-4/5 border border-ink/25 bg-paper p-4"><div className="mb-8 flex gap-1 border-b border-border pb-3"><i className="h-1.5 w-1.5 rounded-full bg-primary"/><i className="h-1.5 w-1.5 rounded-full bg-border"/></div><p className="text-4xl font-semibold">Build for<br/><span className="text-primary">clarity.</span></p></div>:type==="video"?<div className="w-4/5"><div className="aspect-video bg-dark"/><div className="mt-4 flex h-12 gap-1">{[3,1,4,2,5,2].map((n,i)=><i key={i} style={{flex:n}} className="bg-primary/60"/>)}</div></div>:type==="reels"?<div className="flex h-full gap-4">{[1,2,3].map(i=><div key={i} className="aspect-[9/16] h-full border border-border bg-paper p-3"><span className="editorial-label text-primary">0{i}</span></div>)}</div>:type==="graphic"?<div className="text-[clamp(3rem,9vw,8rem)] font-bold leading-none">Aa<span className="text-primary">.</span></div>:type==="brand"?<div className="grid aspect-square w-2/5 place-items-center border border-ink/25"><div className="grid h-20 w-20 place-items-center rounded-full bg-primary text-3xl font-bold text-primary-foreground">F</div></div>:<div className="grid w-full grid-cols-3 gap-4">{["PLAN","CREATE","GROW"].map(x=><div key={x} className="aspect-square border border-border bg-paper p-4 text-xs font-semibold"><span>{x}</span><div className="mt-6 h-px bg-primary"/></div>)}</div>}</div><span className="absolute bottom-4 left-5 text-[10px] uppercase text-ink-soft">{title}</span></div>}
